name: metclim-jupyter-book
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2024.9.24=hecd8cb5_0
  - expat=2.6.3=h6d0c2b6_0
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.4=hcec6c5f_0
  - openssl=3.0.15=h46256e1_0
  - pip=24.2=py312hecd8cb5_0
  - python=3.12.7=hcd54a6c_0
  - readline=8.2=hca72f7f_0
  - setuptools=75.1.0=py312hecd8cb5_0
  - sqlite=3.45.3=h6c40b1e_0
  - tk=8.6.14=h4d00af3_0
  - wheel=0.44.0=py312hecd8cb5_0
  - xz=5.4.6=h6c40b1e_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - accessible-pygments==0.0.5
      - aiobotocore==2.15.2
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiohttp-retry==2.9.1
      - aioitertools==0.12.0
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - anyio==4.6.0
      - appdirs==1.4.4
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - bases==0.3.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - botocore==1.35.36
      - cartopy==0.24.1
      - certifi==2024.8.30
      - cffi==1.17.1
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - dag-cbor==0.3.3
      - dask==2024.11.2
      - debugpy==1.8.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docutils==0.20.1
      - entrypoints==0.4
      - eurec4a==0.0.6
      - executing==2.1.0
      - fasteners==0.19
      - fastjsonschema==2.20.0
      - flexcache==0.3
      - flexparser==0.4
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - ghp-import==2.1.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - intake==0.7.0
      - intake-xarray==0.7.0
      - ipfsspec==0.5.3
      - ipykernel==6.29.5
      - ipython==8.28.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-book==1.0.3
      - jupyter-cache==1.0.0
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-myst==2.4.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - latexcodec==3.0.0
      - linkify-it-py==2.0.3
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.1
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - metpy==1.6.3
      - mistune==3.0.2
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiformats==0.3.1.post4
      - multiformats-config==0.3.1
      - myst-nb==1.1.2
      - myst-parser==2.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netcdf4==1.7.2
      - notebook-shim==0.2.4
      - numcodecs==0.14.0
      - numpy==2.1.2
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - pillow==11.0.0
      - pint==0.24.4
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pure-protobuf==2.3.0
      - pybtex==0.24.0
      - pybtex-docutils==1.0.3
      - pycparser==2.22
      - pydap==3.5.1
      - pydata-sphinx-theme==0.15.4
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pyproj==3.7.0
      - pyshp==2.3.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - s3fs==2024.10.0
      - scipy==1.14.1
      - send2trash==1.8.3
      - shapely==2.0.6
      - six==1.16.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.6
      - sphinx==7.4.7
      - sphinx-book-theme==1.1.3
      - sphinx-comments==0.0.3
      - sphinx-copybutton==0.5.2
      - sphinx-design==0.6.1
      - sphinx-external-toc==1.0.1
      - sphinx-jupyterbook-latex==1.0.0
      - sphinx-multitoc-numbering==0.1.3
      - sphinx-thebe==0.3.1
      - sphinx-togglebutton==0.3.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.6.3
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.35
      - stack-data==0.6.3
      - tabulate==0.9.0
      - terminado==0.18.1
      - tinycss2==1.3.0
      - toolz==1.0.0
      - tornado==6.4.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - typing-validation==1.2.11.post4
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wrapt==1.16.0
      - xarray==2024.9.0
      - yarl==1.17.1
      - zarr==2.18.3
      - zipp==3.20.2
prefix: /Users/martinjanssens/opt/miniconda3/envs/metclim-jupyter-book
